import random
file = open('IdeaGen/PGNouns.txt', 'r')
noun = file.readlines()
file.close()
file = open('IdeaGen/Verbs.txt', 'r')
color = file.readlines()
file.close()
#print(noun)
print(noun[random.randint(0,len(noun)-1)])
print(color[random.randint(0,len(color)-1)])